# Generated by Django 3.0.2 on 2021-03-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxivapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='refid',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='voucher_number',
        ),
    ]
