# Generated by Django 3.0.2 on 2021-03-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxivapp', '0002_auto_20210328_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='account',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='territory',
        ),
        migrations.AddField(
            model_name='customorder',
            name='title',
            field=models.CharField(default=-1, max_length=50, verbose_name='Title '),
            preserve_default=False,
        ),
    ]
