# Generated by Django 3.0.2 on 2021-03-31 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xxivapp', '0003_auto_20210328_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'Features',
                'db_table': 'features',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'product mark',
                'verbose_name_plural': 'product mark',
                'db_table': 'product_mark',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='product_pictures/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pictures', to='xxivapp.Product', verbose_name='product picture')),
            ],
            options={
                'verbose_name': 'ProductPicture',
                'verbose_name_plural': 'ProductPictures',
                'db_table': 'product_pictures',
                'managed': True,
            },
        ),
    ]
