# Generated by Django 3.0.2 on 2021-03-27 03:01

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('phone', models.PositiveIntegerField(null=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('category', models.CharField(blank=True, choices=[('coordinator', 'BUSINESS MANAGER'), ('internal-territory', 'INTERNAL TERRITORY MANAGER'), ('extarnal-territory', 'EXTARNAL TERRITORY MANAGER'), ('aggregator', 'AGGREGATOR'), ('sales-agent', 'SALES AGENT')], max_length=100, null=True, verbose_name='Category')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=100, null=True, verbose_name='Gender')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can connect to this administration site.', verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this user should be treated as active. Deselect this instead of deleting accounts.', verbose_name='active')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Approval')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cell')),
            ],
            options={
                'verbose_name': 'Cell',
                'verbose_name_plural': 'Cells',
                'db_table': 'cells',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='district')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='province')),
            ],
            options={
                'verbose_name': 'province',
                'verbose_name_plural': 'provinces',
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Village')),
                ('cell', models.ForeignKey(db_column='cell', on_delete=django.db.models.deletion.CASCADE, to='authentication.Cell', verbose_name='Cell')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'db_table': 'villages',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='sector')),
                ('district', models.ForeignKey(db_column='district', on_delete=django.db.models.deletion.CASCADE, to='authentication.District', verbose_name='District')),
            ],
            options={
                'verbose_name': 'sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Address like RN4,NM 320, PO.BOX 340 Kigali', max_length=255, null=True, verbose_name='Full Adress')),
                ('tin', models.PositiveIntegerField(blank=True, null=True, verbose_name='TIN Number')),
                ('pin', models.PositiveIntegerField(blank=True, default=12345, null=True, verbose_name='PIN')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('nid', models.BigIntegerField(blank=True, null=True, verbose_name='National ID')),
                ('about', models.TextField(blank=True, help_text='Short description about user', null=True, verbose_name='About user')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Cell', verbose_name='Cell')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.District', verbose_name='District')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Sector', verbose_name='Sector')),
                ('user', models.OneToOneField(blank=True, db_column='user', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(db_column='province', on_delete=django.db.models.deletion.CASCADE, to='authentication.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='cell',
            name='sector',
            field=models.ForeignKey(db_column='sector', on_delete=django.db.models.deletion.CASCADE, to='authentication.Sector', verbose_name='Sectors'),
        ),
    ]
